language: node_js
node_js: 
  - 9
cache:
  directories:
    - node_modules
script:
  - npm run buidl
deploy:
  provider: heroku
  on: production
  api_key:
    secure: ZAOlx+sNqr6ALfWBaEGVZ5//Zeim1UBgKHwhl9vHYcwNAY1jwqcOZDGo5cUObK2sMiYihglu/yTHx2fGHKw1C74DP0ZysABcrejdsFxPsw8KL9P0WcEQ8MnrY8J3s9G/gOCsAk0XH7hOLmJINOvFDaVg0C9eHrxhtAdOr00S6pbc7cqzrpufT/MVQrmYCYu6tt3GhgqHToF3ZFmykSSg7tq2tiGGEndSta5+GNNtif0475YpCFgarcq2dgF4jriuzcVyFj0hnVfQ8KftDJ5Ou6DAPsGFjZ//g4ZpyEz8TsnUhd20UQcW/0/gev2Cum1mZBmTDWkauWFV7g1huNx4BIlg6xVIujUO+OnCvBmMn560ooCjZSrAxI1RvbZfhNpJU0TVmkaqXIRb6l7HpI/KNdD4Cn8FkHWoXlTWU72iwN2MzIZF5jHlVyY0IGVLpFdC71uW3KyhtQPM1sEQ1XU1r2aM+dkQaVuwd7ScRB3JdHCdZOu4ohMzpK1FKdPRswezJp/M9DsQOefpc5DSISlBKtJsKSsBB+745RrjK/7RzBRtdRO7jdHEZrW81Md98K3keeY8OwjOdwyDflMjduvRpV4XHz0t9gFuarTAjDq0IbBGiXrZm/tuAvZ6GFhlBi4T6mRgACN2WuBvgrm9sM4SlAE9hMqYP3jayKRNqziYZRo=
